name: Build Jekyll
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
      - name: Install dependencies
        run: bundle install && bundle exec appraisal install
      - name: Build site
        run: bundle exec appraisal jekyll build --future
